import { describe, it, expect } from 'vitest';
import { formatResultsForCopy, sanitizeCopyText, DISCLAIMER_PATTERNS } from './copyResults';
import type { ReportData } from '@/utils/reportGenerator';

const FORBIDDEN = [
  /for clinical use only/i,
  /not a substitute/i,
  /professional judg/i,
  /consult (a|your) (healthcare|doctor)/i,
  /informational purposes/i,
  /disclaimer/i,
  /tok_/i,
  /https?:\/\//i,
  /cognito/i,
  /generated:/i,
  /spec[- ]?v/i,
];

const sample: ReportData = {
  assessmentName: 'Hamilton Depression Rating Scale (HAM-D)',
  date: '04/10/2026, 16:00:00',
  totalScore: '14/52',
  severity: 'Mild Depression',
  interpretation: 'Mild depressive symptoms. This is for informational purposes only.',
  sections: [
    { title: 'Positive Findings', items: ['Depressed mood — Present on questioning (Score: 1/4)', 'Insomnia (Score: 2/2)'], type: 'positive' },
    { title: 'Negative Findings', items: ['Guilt (Score: 0)'], type: 'negative' },
    { title: 'Items Not Assessed', items: ['Weight loss'], type: 'not-assessed' },
    { title: 'Notes', items: ['Not a substitute for professional judgment. See https://example.org'], type: 'info' },
  ],
  disclaimer: 'For clinical use only. Consult a healthcare provider.',
};

describe('copy results text', () => {
  it('contains only result values from ReportData', () => {
    const text = formatResultsForCopy(sample);
    expect(text.split('\n')).toEqual([
      'Hamilton Depression Rating Scale (HAM-D)',
      'Depressed mood: Present on questioning (1/4)',
      'Insomnia: 2/2',
      'Guilt: 0',
      'Total score: 14/52',
      'Interpretation: Mild Depression',
    ]);
    FORBIDDEN.forEach((re) => expect(text).not.toMatch(re));
  });

  it('strips disclaimers, branding, URLs, timestamps, tokens, markdown, emoji and N/A padding from free text', () => {
    const raw = [
      '## **CASES Tool - Clinical Report** ✅',
      '——————————————',
      'Date: 04/10/2026',
      'Generated: 2026-10-04T10:30:00Z',
      '',
      '- [YES] Drug-resistant epilepsy',
      '- [UNANSWERED] Seizure frequency',
      '  • Item 3: N/A (Not rated)',
      'Total Criteria Met: 4 of 6 tok_9f8a7b6c',
      'Clinical Impression: Appropriate for Surgical Referral',
      'Spec version: 2.1',
      'Disclaimer: This tool is not a substitute for clinical judgment.',
      'Note: For clinical use only. Consult a healthcare provider.',
      'This content is for informational purposes only.',
      'Reference: Smith et al. https://doi.org/10.1000/xyz',
      'Generated by Cognito — Clinical Assessment Toolkit',
      '© 2026 Cognito. All rights reserved.',
    ].join('\n');
    const text = sanitizeCopyText(raw);
    expect(text.split('\n')).toEqual([
      'CASES Tool - Clinical Report',
      'Drug-resistant epilepsy: Yes',
      'Total Criteria Met: 4 of 6',
      'Clinical Impression: Appropriate for Surgical Referral',
    ]);
    FORBIDDEN.forEach((re) => expect(text).not.toMatch(re));
    DISCLAIMER_PATTERNS.forEach((re) => expect(text).not.toMatch(re));
  });

  it('keeps result sentences while removing trailing disclaimer sentences', () => {
    const text = sanitizeCopyText('Impression: Abnormalities on 2 module(s). Interpret in the context of the full neurological examination.');
    expect(text).toBe('Impression: Abnormalities on 2 module(s).');
  });

  it('folds list items under a header into one "Item: value" line', () => {
    const raw = 'Hunter Criteria\nClinical criteria present:\n  • Clonus\n  • Hyperthermia\nImplicated agent(s):\n  • None selected\nVerdict: Hunter Criteria MET';
    expect(sanitizeCopyText(raw)).toBe('Hunter Criteria\nClinical criteria present: Clonus, Hyperthermia\nVerdict: Hunter Criteria MET');
  });

  it('is idempotent', () => {
    const once = formatResultsForCopy(sample);
    expect(sanitizeCopyText(once)).toBe(once);
  });
});
